### PR TITLE
[WIP] Swift 5

### PR DESCRIPTION
**Pull request by DivineDominion**
Will be mostly dependency updates and project setting fixes.

### CODE REVIEW

**Comment by DivineDominion** [comment]
Sheesh. This Travis stuff is making me nuts. @mdiep I think I did everything on the source side; can you try to make the CI work? If it helps, we can merge this into a swift-5 branch in this repo instead of my fork and work together.

**Comment by mdiep** [comment]
I will try to take a look in the next couple days. 👍

**Comment by mattrubin** [comment]
The build break is caused by a change to the `attributes` argument type of `FileManager`'s `createDirectory(at:withIntermediateDirectories:attributes:)` method. You can see the fix here: https://github.com/SwiftGit2/SwiftGit2/pull/145/files#diff-57281f3464341399c942568b729d1668R62

(I didn't realize this PR was already in progress when I created https://github.com/SwiftGit2/SwiftGit2/pull/145 and https://github.com/SwiftGit2/SwiftGit2/pull/146)

**Comment by mdiep** [comment]
@DivineDominion Thanks for your work on this! @mattrubin's PRs had green CI builds, so I went ahead and merged them. But I appreciate the effort!

**Comment by mattrubin** [comment]
@DivineDominion Thank you for this PR! My apologies for not noticing it before I went ahead with my own.

**Comment by DivineDominion** [comment]
🙌  I'm happy that things work now, that's what really counts :)

**Pull request closed without merging**
