### PR TITLE
[DO NOT MERGE] Pull Push

### PR DESCRIPTION
**Pull request by tengyifei**

### CODE REVIEW

**Comment by mdiep** [comment]
Is this ready to be reviewed?

**Comment by tengyifei** [comment]
No still researching how to retrieve the list of conflicts during a merge.
Got an idea?

**Comment by arguiot** [comment]
Any update here? Really looking for pull & push features on SwiftGit2. Otherwise, is there anything I can do to "emulate" this feature natively or by using ObjectiveGit?

**Comment by BilalReffas** [comment]
Feel free to open it again, if you figured out  😊

**Pull request closed without merging**
