### PR TITLE
Support for Swift Package Manager

### PR DESCRIPTION
**Pull request by muizidn**
This PR is continuation of #158

Changes in this PR including
1. Update libgit2 directory to Clibgit2 to match SwiftPM rule and update Xcodeproj setting to point new updated path.
2. Add Package.swift file. To automate task, we need to incorporate SPMCLI files.

SwiftPM doesn't support mixed source package. Hence, we rename SwiftPackage2/*.swift files to SwiftPackage2/Swift/*.swift.

### CODE REVIEW

**Comment by mdiep** [comment]
It doesn't look like this is include the obj-c file, so this would be missing the libgit2 init call?

**Comment by muizidn** [comment]
@mdiep I've just re-read Swift Package Manager PackageDescription. It looks like in 5.0, passing CXX settings is supported. I'll figure out to apply it in the PR.

**Comment by daveanderson** [comment]
Can't wait to see this land. Anything I can do to help?

**Comment by mxcl** [comment]
I reviewed it and it looks good, and should be completely safe for existing users, can we get this? Need it for a script I'm writing.

**Comment by mdiep** [comment]
@mxcl I've invited you to be a member of SwiftGit2. Feel free to merge!

**Comment by muizidn** [comment]
@mxcl What can I do to help?

**Comment by liamnichols** [comment]
Any idea if there is a way to stretch this to supporting iOS in Xcode 11? From what I can tell, this won't currently work with it.

I've had a dig around and haven't had much luck but I'm assuming that we would need to be able to compile everything via `swift build` in order to achieve that which is maybe unrealistic? Compiling C projects isn't one of my strong points though so maybe its doable and I've missed things? 

Might just be easier to wait until SPM supports precompiled packages 😅

**Comment by mackoj** [comment]
Now that Swift PM has way more capabilities with the last Xcode 11.4 could this merge be updated to work with it ? @muizidn

**Comment by maxvol** [comment]
would you please also make a new release?

**Comment by mdiep** [comment]
Unfortunately, my job at Apple prevents me from participating in open source. But maybe one of the other contributors can make a new release. Otherwise, if someone with a reputable GitHub account wants access, I'm happy to add them as a maintainer.

**Comment by maxvol** [comment]
@mdiep i will probably not actively contribute, but i can make releases if you add me as a maintainer. hopefully my account is sufficiently reputable ;)

**Comment by mackoj** [comment]
Maybe you should ask to other big contributors to this project like @mattrubin ?
As @maxvol says I can do the releases/code review but I don't think I will do a lot more.

**Comment by cameroncooke** [comment]
Any update on this, really need SPM support.

**Comment by BilalReffas** [comment]
Hi Folks, will go back to you after [#168](https://github.com/SwiftGit2/SwiftGit2/pull/168) is merged asap, I promise.

**Comment by BilalReffas** [comment]
@muizidn Because of inactivity I forked you changes they added [here](https://github.com/SwiftGit2/SwiftGit2/pull/170/files)

Will close this PR therefore.

**Pull request closed without merging**
