### PR TITLE
Fix misunderstanding of pointer-to-pointer lifetime

### LINKED ISSUE #175: Swift 5.3 support
SwiftGit2 can't compile using the Swift 5.3 compiler. I'm using the `master` branch of this repository and I'm getting the following build error (formatted by XCPretty to be human-readable):
```
❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:592:36: cannot convert value of type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>' to expected argument type 'UnsafeMutablePointer<Int8>'

                var paths = withExtendedLifetime(&dirPointer) {
           ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:593:26: cannot convert value of type 'UnsafeMutablePointer<Int8>' to expected argument type 'Optional<UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>>'

                        git_strarray(strings: $0, count: 1)
                                                 ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:592:36: cannot convert value of type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>' to expected argument type 'UnsafeMutablePointer<Int8>'

                var paths = withExtendedLifetime(&dirPointer) {
                                              ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:593:26: cannot convert value of type 'UnsafeMutablePointer<Int8>' to expected argument type 'Optional<UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>>'

                        git_strarray(strings: $0, count: 1)
                                                 ^
```

According to my experience with this kind of error, it really shouldn't be hard to fix. It's just weird that the compiler is asking for a double `UnsafeMutablePointer` 🤷‍♂️

### PR DESCRIPTION
**Pull request by belkadan**
Fixes #175

### CODE REVIEW

**Comment by DivineDominion** [comment]
I can attest this build with Xcode 12 and also works in the app that is built with it :)

**Comment by yonihemi** [comment]
@kareman Can we have this PR merged? It's essential for building in Xcode 12 / Swift 5.3

**Comment by kareman** [comment]
I don't have merge access

**Comment by kareman** [comment]
@BilalReffas can you merge this?

**Comment by BilalReffas** [comment]
Thanks @kareman 🍻

**Pull request merged**
