### PR TITLE
Update Project to Swift 4.2

### PR DESCRIPTION
**Pull request by DivineDominion**
Not much to do here

### CODE REVIEW

**Comment by mdiep** [comment]
Unfortunately the macOS build failed. 😞 

We might need to move to a newer Travis image.

**Comment by arguiot** [comment]
@DivineDominion I've sent a PR to your forked repo that updates Result, so it's compatible with Swift 4.2

**Comment by DivineDominion** [comment]
@mdiep I updated the PR accordingly.

**Comment by mdiep** [comment]
```
⚠️  /Users/travis/build/SwiftGit2/SwiftGit2/External/libgit2/src/unix/posix.h:86:9: 'futimens' is only available on macOS 10.13 or newer [-Wunguarded-availability-new]
        return futimens(f, s);
```

It looks like we may need to bump up the deployment target?

**Comment by DivineDominion** [comment]
I think I give up on fixing Travis build in my life at this point :) Always a puzzle. You're right, the latest job still fails, even though Xcode 10.1 is used and macOS 10.13 as well (as [per the xcode-setting](https://docs.travis-ci.com/user/reference/osx/#macos-version), not the os-setting in the YML config file, of course ... ... ... (insert disappointed stare here) ...):
https://travis-ci.org/SwiftGit2/SwiftGit2/jobs/515265488

The log is too long to be displayed, by the way; someone with more Travis experience than I should do something about that :)

Not sure what this is about and why my local, freshly checked-out build works. macOS 10.13 is used by Travis, so ¯\\_(ツ)_/¯

The only thing I know that should affect the build is to use `osx_image: xcode10.2` which will make Travis compile on 10.14

**Comment by mdiep** [comment]
I have no problem jumping straight to Swift 5

**Comment by DivineDominion** [comment]
Ok. Building ZipArchive causes trouble in the time being unless this is merged: https://github.com/ZipArchive/ZipArchive/pull/500

**Comment by mdiep** [comment]
Looks like that was merged and release. 😃

**Comment by DivineDominion** [comment]
This is like detective work, only I am both detective and the suspect leaving trails :) Will be working on a Swift 5 branch now :)

**Pull request closed without merging**
