### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by mattrubin**
Update the source and dependencies to build with Swift 3.

This PR does not update SwiftGit2 to follow the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/).

### CODE REVIEW

**Comment by mdiep** [comment]
Loving all these PRs!

**Comment by mattrubin** [comment]
@mdiep They may slow down a bit now that the updating is done and I'm into actually *using* the code, but I'll keep opening PRs whenever I make improvements!

**Comment by mdiep** [comment]
Are you interested in trying to update the API to follow the API guidelines? If not, I'll try to find time to do so.

**Comment by mattrubin** [comment]
Oh, I already have a branch in progress for that. 😄

**Pull request merged**
