### PR TITLE
Swift 2.3

### PR DESCRIPTION
**Pull request by mattrubin**
Update the source and dependencies for Xcode 8 and Swift 2.3.

### CODE REVIEW

**Comment by mdiep** [comment]
This is great! Thanks for the PR! I obviously haven't had time to do this myself, but I'd love for this project to live on. (And will happily review PRs.)

Can you update `.travis.yml` to build with Xcode 8 on CI?

**Comment by mattrubin** [comment]
Travis now builds with Xcode 8.1.

I also [fixed a bug with `cibuild`](https://github.com/SwiftGit2/SwiftGit2/pull/64/commits/6e0d67ae2fed39d4e1690676e6b7daa0f29d9638) where Travis would [report success even if `xcodebuild` failed](https://travis-ci.org/SwiftGit2/SwiftGit2/builds/181735503).

**Comment by mattrubin** [comment]
It seems that Travis is building the frameworks, but not running any tests. I'm going to look into porting over the changes made to https://github.com/libgit2/objective-git/blob/master/script/cibuild since the scripts were last synced.

**Comment by mattrubin** [comment]
This PR now includes the build script updates from #65, and no longer requires a fork of [modocache/Guanaco](https://github.com/modocache/Guanaco).

@mdiep: I believe this is ready for review!

**Pull request merged**
