### PR TITLE
Add support for Travis CI

### PR DESCRIPTION
**Pull request by JrGoodle**
Addresses #48

### CODE REVIEW

**Comment by JrGoodle** [comment]
@mdiep The `scan` command worked for me locally, but I can't test on Travis right now. Travis CI needs to be enabled for this repository, and some settings need to be tweaked so Travis will run jobs for pull requests.

screenshot 2016-01-25 17 58 52

**Comment by mdiep** [comment]
Travis should be properly configured now. Thanks for tackling this!

**Comment by JrGoodle** [comment]
@mdiep Thanks for configuring Travis. I got the job to pass, but it doesn't work with the bootstrap script so I specified things manually. I think this is probably good for now to just get things up and running, but I'm guessing someone may eventually want to consolidate things into the scripts.

**Comment by mdiep** [comment]
Thanks! This is a good start.

**Pull request merged**
